version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      farmjs:
        patterns:
          - "@farm.js/*"
    open-pull-requests-limit: 5
